# Generated by Django 5.2.8 on 2025-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_participant_alter_event_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='no_imgae.jpg', null=True, upload_to=''),
        ),
    ]
